[build]
  command = "npm run build"
  publish = "dist/spa"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  AIRTABLE_API_TOKEN = "REPLACE_ENV.AIRTABLE_API_TOKEN"
  AIRTABLE_BASE_ID = "app0PK34gyJDizR3Q"
  AIRTABLE_TABLE_ORDERS = "tbl01DTvrGtsAaPfZ"
  AIRTABLE_TABLE_COMPANIES = "tbljtdHPdHnTberDy"
  AIRTABLE_TABLE_TRANSFER_FORMS = "tblK7lUO1cfNFYO14"
